version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: postgresql://postgres:postgres@postgres:5432/postgres?schema=public
      JWT_SECRET: sua_chave_secreta_jwt
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
